# Generated by Django 4.1.1 on 2022-10-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок статьи')),
                ('description', models.CharField(max_length=250, verbose_name='Краткое описание статьи')),
                ('text', models.TextField(verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Список статей',
                'verbose_name_plural': 'Список статей',
            },
        ),
    ]
