# Generated by Django 4.1.1 on 2022-10-03 10:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Статья'),
        ),
    ]
