# Generated by Django 4.1.1 on 2022-10-04 07:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Список категорий',
                'verbose_name_plural': 'Список категорий',
            },
        ),
        migrations.CreateModel(
            name='CategoryArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок статьи')),
                ('description', models.CharField(max_length=250, verbose_name='Краткое описание статьи')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Список категорий',
                'verbose_name_plural': 'Список категорий',
            },
        ),
    ]
