# Generated by Django 4.1.1 on 2022-10-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Список категорий', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='categoryarticles',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='categoryarticles',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Education.categories'),
        ),
    ]
