# Generated by Django 4.1.1 on 2022-10-04 09:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок статьи')),
                ('description', models.CharField(max_length=250, verbose_name='Краткое описание статьи')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Статья')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Education.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.DeleteModel(
            name='CategoryArticles',
        ),
    ]
